# HER2 Attention Classifier - Data processing & Training Pipeline

## 1. Notebook Setup and Configuration

In [1]:
%load_ext autoreload
%autoreload

### 1.1 Import Libraries

In [2]:
import pandas as pd
from pathlib import Path
import openpyxl
from IPython.display import display, HTML, Image
import gc
import sys
import os
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

### 1.2 Project Imports

In [3]:
from src.dataloader.discover_wsi import discover_wsi_paths
from src.dataloader.wsi_reader import WSIReader, read_wsi_region
from src.preprocessing.macenko import get_macenko_vectors, macenko_stain_normalize, estimate_reference_stain_vectors

### 1.3 Processing Configuration

Define parameters for patch extraction and stain normalization.

In [4]:
# Patch extraction parameters
PATCHES_PER_SLIDE = 20
PATCH_SIZE = 256
LEVEL_REFERENCE = 2          # Level for reference vector calculation
LEVEL_ANALYSIS = 0            # Level for patch analysis/training
SEED = 42                      # Random seed for reproducibility

# Output directories
OUTPUT_BASE = Path('outputs/preprocessing')
OUTPUT_BASE.mkdir(parents=True, exist_ok=True)

## 2. Helper Functions

### 2.1 HER2 Status Detection

In [5]:
def get_tcga_her2_status(case_name):
    """
    Extract HER2 status from TCGA metadata Excel file.
    
    Args:
        case_name (str): TCGA case ID (e.g., 'TCGA-A1-A0SP')
    
    Returns:
        int: 1 for Positive, 0 for Negative, 1 as default
    """
    try:
        wb = openpyxl.load_workbook('data\\TCGA_BRCA_Filtered\\case&annotation_counts_clean.xlsx')
        ws = wb.active
        for row in ws.iter_rows(min_row=2, values_only=True):
            if row[0] == case_name:
                if row[1] == 'Positive':
                    return 1
                elif row[1] == 'Negative':
                    return 0
                else:
                    return 1
    except Exception:
        pass
    return 1  # Default to positive if not found

## 3. Data Discovery and Metadata

### 3.1 Discover WSI Files

In [6]:
# Discover all WSI files in the data directory
paths_df = discover_wsi_paths('data', '.svs')

print(f"Found {len(paths_df)} WSI files")
print(f"\nDataset breakdown by source:")

if 'parent_dir' in paths_df.columns:
    group_col = 'parent_dir'
elif 'folder' in paths_df.columns:
    group_col = 'folder'
else:
    paths_df['source_dir'] = paths_df['full_path'].apply(lambda x: Path(x).parent.name)
    group_col = 'source_dir'

for source in paths_df[group_col].unique():
    count = len(paths_df[paths_df[group_col] == source])
    print(f"  {source}: {count} slides")

display(paths_df.head())

Searching for files with extensions .svs in 'data'...
Found 471 WSI files.
Found 471 WSI files

Dataset breakdown by source:
  SVS: 471 slides

,full_path,file_name,source_dir
0,data\TCGA_BRCA_Filtered\SVS\TCGA-A1-A0SP-01Z-0...,TCGA-A1-A0SP-01Z-00-DX1.20D689C6-EFA5-4694-BE7...,SVS
1,data\TCGA_BRCA_Filtered\SVS\TCGA-A2-A04W-01Z-0...,TCGA-A2-A04W-01Z-00-DX1.F7E7B945-2ADC-4741-8FC...,SVS
2,data\TCGA_BRCA_Filtered\SVS\TCGA-A2-A04X-01Z-0...,TCGA-A2-A04X-01Z-00-DX1.E01A4522-67B3-4FEF-BD6...,SVS
3,data\TCGA_BRCA_Filtered\SVS\TCGA-A2-A0CX-01Z-0...,TCGA-A2-A0CX-01Z-00-DX1.F07C75AB-E568-45CB-B49...,SVS
4,data\TCGA_BRCA_Filtered\SVS\TCGA-A2-A0EY-01Z-0...,TCGA-A2-A0EY-01Z-00-DX1.2F2428B3-0767-48E0-AC2...,SVS

### 3.2 Add HER2 Status Annotation

In [7]:
# Extract case names from filenames
paths_df['case_name'] = paths_df['file_name'].str.split('.').str[0]

# Determine HER2 status based on filename and metadata
paths_df['her2_status'] = paths_df['case_name'].apply(
    lambda x: 0 if x.startswith('Her2Neg') else (
        1 if x.startswith('Her2Pos') else (
            get_tcga_her2_status(x) if x.startswith('TCGA') else 1
        )
    )
)

# Save metadata
wsi_metadata_path = 'outputs/dataloader/wsi_paths.csv'
Path(wsi_metadata_path).parent.mkdir(parents=True, exist_ok=True)
paths_df.to_csv(wsi_metadata_path, index=False)

print(f"HER2 Status Distribution:")
print(paths_df['her2_status'].value_counts().sort_index())
print(f"  HER2 Positive: {(paths_df['her2_status'] == 1).sum()} slides")
print(f"  HER2 Negative: {(paths_df['her2_status'] == 0).sum()} slides")
print(f"\nWSI metadata saved to: {wsi_metadata_path}")

gc.collect()
display(paths_df.head())

HER2 Status Distribution:
her2_status
0    189
1    282
Name: count, dtype: int64
  HER2 Positive: 282 slides
  HER2 Negative: 189 slides

WSI metadata saved to: outputs/dataloader/wsi_paths.csv

,full_path,file_name,source_dir,case_name,her2_status
0,data\TCGA_BRCA_Filtered\SVS\TCGA-A1-A0SP-01Z-0...,TCGA-A1-A0SP-01Z-00-DX1.20D689C6-EFA5-4694-BE7...,SVS,TCGA-A1-A0SP-01Z-00-DX1,0
1,data\TCGA_BRCA_Filtered\SVS\TCGA-A2-A04W-01Z-0...,TCGA-A2-A04W-01Z-00-DX1.F7E7B945-2ADC-4741-8FC...,SVS,TCGA-A2-A04W-01Z-00-DX1,1
2,data\TCGA_BRCA_Filtered\SVS\TCGA-A2-A04X-01Z-0...,TCGA-A2-A04X-01Z-00-DX1.E01A4522-67B3-4FEF-BD6...,SVS,TCGA-A2-A04X-01Z-00-DX1,1
3,data\TCGA_BRCA_Filtered\SVS\TCGA-A2-A0CX-01Z-0...,TCGA-A2-A0CX-01Z-00-DX1.F07C75AB-E568-45CB-B49...,SVS,TCGA-A2-A0CX-01Z-00-DX1,1
4,data\TCGA_BRCA_Filtered\SVS\TCGA-A2-A0EY-01Z-0...,TCGA-A2-A0EY-01Z-00-DX1.2F2428B3-0767-48E0-AC2...,SVS,TCGA-A2-A0EY-01Z-00-DX1,1

# 4. Stain Normalization and Patch Extraction Pipeline

## 4. Stain Normalization and Patch Extraction

### Pipeline Overview
1. **Step 1**: Extract patches from all slides at Level 2 to calculate reference stain vectors
2. **Step 2**: Extract patches at Level 0 and normalize using the global reference vectors

### Processing Notes
- **Level 2** patches: Used for reference calculation (lower resolution, faster)
- **Level 0** patches: High resolution patches for model training
- **Memory Management**: Aggressive garbage collection after each slide
- **Reproducibility**: Fixed random seed for consistent patch sampling

In [9]:
all_patches_for_reference = []
successful_slides = 0

print(f"Configuration:")
print(f"  Patches per slide: {PATCHES_PER_SLIDE}")
print(f"  Patch size: {PATCH_SIZE} × {PATCH_SIZE}")
print(f"  Reference level: {LEVEL_REFERENCE}")
print(f"  Random seed: {SEED}")

# Extract patches from ALL slides for reference calculation
for idx, path in enumerate(tqdm(paths_df['full_path'], desc="Collecting reference patches")):
    try:
        with WSIReader(path, prefer_cucim=False) as reader:
            width, height = reader.dimensions
            np.random.seed(SEED + idx)
            
            # Get PATCHES_PER_SLIDE random patches at LEVEL_REFERENCE
            patches_from_slide = 0
            for patch_idx in range(PATCHES_PER_SLIDE):
                try:
                    x = np.random.randint(0, max(1, width - PATCH_SIZE))
                    y = np.random.randint(0, max(1, height - PATCH_SIZE))
                    
                    patch = reader.read_region(x=x, y=y, level=LEVEL_REFERENCE, size=PATCH_SIZE)
                    
                    # Filter out low-quality patches (mostly white/background)
                    # Check if patch has sufficient color variation
                    if patch.std() > 5:  # Minimum standard deviation threshold
                        all_patches_for_reference.append(patch)
                        patches_from_slide += 1
                except Exception:
                    continue
            
            if patches_from_slide > 0:
                successful_slides += 1
        
        gc.collect()
    
    except Exception as e:
        pass

print(f"\nReference collection complete:")
print(f"  Slides processed: {successful_slides}/{len(paths_df)}")
print(f"  Total reference patches: {len(all_patches_for_reference)}")

# Calculate reference stain vectors from all patches with error handling
reference_stain_vectors = None
if len(all_patches_for_reference) > 0:
    try:
        reference_stain_vectors = estimate_reference_stain_vectors(all_patches_for_reference)
        print(f"  Reference stain vectors: {reference_stain_vectors.shape}")
        print(f"\n  Stain vector 1 (Hematoxylin):\n    {reference_stain_vectors[0]}")
        print(f"\n  Stain vector 2 (Eosin):\n    {reference_stain_vectors[1]}")
    except IndexError as e:
        print(f"  WARNING: Could not compute reference vectors from patches: {e}")
        print(f"  Patches may lack sufficient color variation.")
        print(f"  Will use per-slide normalization instead.")
        reference_stain_vectors = None
else:
    print("  ERROR: No patches collected for reference!")
    reference_stain_vectors = None

# Clear reference patches from memory
all_patches_for_reference.clear()
gc.collect()

# Save reference stain vectors
if reference_stain_vectors is not None:
    ref_vectors_path = (OUTPUT_BASE / 'reference_stain_vectors.npy')
    np.save(ref_vectors_path, reference_stain_vectors)
    print(f"✓ Reference stain vectors saved to: {ref_vectors_path}")
else:
    print(f"⚠ Reference stain vectors not saved (using per-slide normalization)")




gc.collect()
print(f"\nMemory cleaned up!")

Configuration:
  Patches per slide: 20
  Patch size: 256 × 256
  Reference level: 2
  Analysis level: 0
  Random seed: 42

Collecting reference patches:  82%|████████▏ | 385/471 [01:09<00:14,  5.78it/s]c:\Users\tanth\Desktop\her2-attention-classifier\src\dataloader\wsi_reader.py:156: UserWarning: OpenSlide available but failed to load slide: OpenSlideUnsupportedFormatError: Unsupported or missing image file
  warnings.warn(f"OpenSlide available but failed to load slide: {type(e).__name__}: {e}")
c:\Users\tanth\Desktop\her2-attention-classifier\src\dataloader\wsi_reader.py:156: UserWarning: OpenSlide available but failed to load slide: OpenSlideUnsupportedFormatError: Unsupported or missing image file
  warnings.warn(f"OpenSlide available but failed to load slide: {type(e).__name__}: {e}")
Collecting reference patches: 100%|██████████| 471/471 [01:24<00:00,  5.58it/s]

Reference collection complete:
  Slides processed: 469/471
  Total reference patches: 6528
  Reference stain vectors: (2, 3)

  Stain vector 1 (Hematoxylin):
    [0.88926035 0.08698494 0.44905424]

  Stain vector 2 (Eosin):
    [0.11073965 0.91301506 0.55094576]
✓ Reference stain vectors saved to: outputs\preprocessing\reference_stain_vectors.npy

Memory cleaned up!
  Reference stain vectors: (2, 3)

  Stain vector 1 (Hematoxylin):
    [0.88926035 0.08698494 0.44905424]

  Stain vector 2 (Eosin):
    [0.11073965 0.91301506 0.55094576]
✓ Reference stain vectors saved to: outputs\preprocessing\reference_stain_vectors.npy

Memory cleaned up!

In [ ]:
# Track extracted patches metadata
extracted_data = {
    'slide_name': [],
    'case_name': [],
    'her2_status': [],
    'patch_index': [],
    'x_coord': [],
    'y_coord': [],
}

# Extract patches at level 0 for analysis/training
successful_extractions = 0
failed_extractions = 0

for idx, (path, case_name, her2_status) in enumerate(zip(
    paths_df['full_path'], 
    paths_df['case_name'], 
    paths_df['her2_status']
)):
    try:
        with WSIReader(path, prefer_cucim=False) as reader:
            width, height = reader.dimensions
            slide_name = Path(path).name
            
            # Set random seed for reproducibility
            np.random.seed(SEED + idx)
            
            # Extract PATCHES_PER_SLIDE random patches at LEVEL_ANALYSIS
            for patch_idx in range(PATCHES_PER_SLIDE):
                try:
                    # Random coordinates
                    x = np.random.randint(0, max(1, width - PATCH_SIZE))
                    y = np.random.randint(0, max(1, height - PATCH_SIZE))
                    
                    # Read patch at high resolution
                    patch = reader.read_region(x=x, y=y, level=LEVEL_ANALYSIS, size=PATCH_SIZE)
                    
                    # Normalize patch using reference vectors
                    if reference_stain_vectors is not None:
                        normalized_patch = macenko_stain_normalize(
                            patch, 
                            reference_stain_vectors=reference_stain_vectors
                        )
                    else:
                        normalized_patch = macenko_stain_normalize(patch)
                    
                    # Store metadata
                    extracted_data['slide_name'].append(slide_name)
                    extracted_data['case_name'].append(case_name)
                    extracted_data['her2_status'].append(her2_status)
                    extracted_data['patch_index'].append(patch_idx)
                    extracted_data['x_coord'].append(x)
                    extracted_data['y_coord'].append(y)
                    
                    successful_extractions += 1
                    
                    # Free memory immediately after processing
                    del patch, normalized_patch
                
                except Exception:
                    failed_extractions += 1
                    continue
        
        # Force garbage collection after each slide
        gc.collect()
    
    except Exception as e:
        pass

# Create metadata dataframe
patch_metadata_df = pd.DataFrame(extracted_data)

print(f"\nPatch extraction complete:")
print(f"  Successful extractions: {successful_extractions}")
print(f"  Failed extractions: {failed_extractions}")
print(f"  Total patches: {len(patch_metadata_df)}")

# Analyze extracted patches by HER2 status
print(f"\nPatches by HER2 Status:")
status_counts = patch_metadata_df['her2_status'].value_counts().sort_index()
for status, count in status_counts.items():
    label = "Positive" if status == 1 else "Negative"
    print(f"  HER2 {label}: {count} patches")

# Display sample
print(f"\nSample of extracted patches metadata:")
display(patch_metadata_df.head(10))

# Save metadata
patch_metadata_path = (OUTPUT_BASE / 'patch_metadata.csv')
patch_metadata_df.to_csv(patch_metadata_path, index=False)
print(f"\n✓ Patch metadata saved to: {patch_metadata_path}")# Track extracted patches metadata
extracted_data = {
    'slide_name': [],
    'case_name': [],
    'her2_status': [],
    'patch_index': [],
    'x_coord': [],
    'y_coord': [],
}

# Extract patches at level 0 for analysis/training
successful_extractions = 0
failed_extractions = 0

for idx, (path, case_name, her2_status) in enumerate(zip(
    paths_df['full_path'], 
    paths_df['case_name'], 
    paths_df['her2_status']
)):
    try:
        with WSIReader(path, prefer_cucim=False) as reader:
            width, height = reader.dimensions
            slide_name = Path(path).name
            
            # Set random seed for reproducibility
            np.random.seed(SEED + idx)
            
            # Extract PATCHES_PER_SLIDE random patches at LEVEL_ANALYSIS
            for patch_idx in range(PATCHES_PER_SLIDE):
                try:
                    # Random coordinates
                    x = np.random.randint(0, max(1, width - PATCH_SIZE))
                    y = np.random.randint(0, max(1, height - PATCH_SIZE))
                    
                    # Read patch at high resolution
                    patch = reader.read_region(x=x, y=y, level=LEVEL_ANALYSIS, size=PATCH_SIZE)
                    
                    # Normalize patch using reference vectors
                    if reference_stain_vectors is not None:
                        normalized_patch = macenko_stain_normalize(
                            patch, 
                            reference_stain_vectors=reference_stain_vectors
                        )
                    else:
                        normalized_patch = macenko_stain_normalize(patch)
                    
                    # Store metadata
                    extracted_data['slide_name'].append(slide_name)
                    extracted_data['case_name'].append(case_name)
                    extracted_data['her2_status'].append(her2_status)
                    extracted_data['patch_index'].append(patch_idx)
                    extracted_data['x_coord'].append(x)
                    extracted_data['y_coord'].append(y)
                    
                    successful_extractions += 1
                    
                    # Free memory immediately after processing
                    del patch, normalized_patch
                
                except Exception:
                    failed_extractions += 1
                    continue
        
        # Force garbage collection after each slide
        gc.collect()
    
    except Exception as e:
        pass

# Create metadata dataframe
patch_metadata_df = pd.DataFrame(extracted_data)

print(f"\nPatch extraction complete:")
print(f"  Successful extractions: {successful_extractions}")
print(f"  Failed extractions: {failed_extractions}")
print(f"  Total patches: {len(patch_metadata_df)}")

# Analyze extracted patches by HER2 status
print(f"\nPatches by HER2 Status:")
status_counts = patch_metadata_df['her2_status'].value_counts().sort_index()
for status, count in status_counts.items():
    label = "Positive" if status == 1 else "Negative"
    print(f"  HER2 {label}: {count} patches")

# Display sample
print(f"\nSample of extracted patches metadata:")
display(patch_metadata_df.head(10))

# Save metadata
patch_metadata_path = (OUTPUT_BASE / 'patch_metadata.csv')
patch_metadata_df.to_csv(patch_metadata_path, index=False)
print(f"\n✓ Patch metadata saved to: {patch_metadata_path}")