## Notebook setup

### Import statements

In [1]:
import pandas as pd
from pathlib import Path
import openpyxl
from IPython.display import display, HTML, Image

from src.dataloader.discover_wsi import discover_wsi_paths

### Function declarations

In [2]:
def get_tcga_her2_status(case_name):
    wb = openpyxl.load_workbook('data\\TCGA_BRCA_Filtered\\case&annotation_counts_clean.xlsx')
    ws = wb.active
    # Assume the first column is case_name, second column is her2_status
    for row in ws.iter_rows(min_row=2, values_only=True):
        if row[0] == case_name:
            # Convert status to numeric: Positive=1, Negative=0
            if row[1] == 'Positive':
                return 1
            elif row[1] == 'Negative':
                return 0
            else:
                return 1  # default if value is unexpected
    return 1  # default if not found

## Discover WSI paths and data manipulation

In [3]:
paths_df = discover_wsi_paths('data','outputs/dataload/wsi_paths.csv','.svs')
display(paths_df.head())

Searching for files with extensions .svs in 'data'...
Found 316 WSI files. Paths and names saved to 'outputs/dataload/wsi_paths.csv'.

,relative_path,file_name
0,TCGA_BRCA_Filtered\SVS\TCGA-A1-A0SP-01Z-00-DX1...,TCGA-A1-A0SP-01Z-00-DX1.20D689C6-EFA5-4694-BE7...
1,TCGA_BRCA_Filtered\SVS\TCGA-A2-A04W-01Z-00-DX1...,TCGA-A2-A04W-01Z-00-DX1.F7E7B945-2ADC-4741-8FC...
2,TCGA_BRCA_Filtered\SVS\TCGA-A2-A04X-01Z-00-DX1...,TCGA-A2-A04X-01Z-00-DX1.E01A4522-67B3-4FEF-BD6...
3,TCGA_BRCA_Filtered\SVS\TCGA-A2-A0CX-01Z-00-DX1...,TCGA-A2-A0CX-01Z-00-DX1.F07C75AB-E568-45CB-B49...
4,TCGA_BRCA_Filtered\SVS\TCGA-A2-A0EY-01Z-00-DX1...,TCGA-A2-A0EY-01Z-00-DX1.2F2428B3-0767-48E0-AC2...

In [4]:
paths_df['case_name'] = paths_df['file_name'].str.split('.').str[0]

paths_df['her2_status'] = paths_df['case_name'].apply(
    lambda x: 0 if x.startswith('Her2Neg') else (
        1 if x.startswith('Her2Pos') else (
            get_tcga_her2_status(x) if x.startswith('TCGA') else 1
        )
    )
)
display(paths_df.head())

,relative_path,file_name,case_name,her2_status
0,TCGA_BRCA_Filtered\SVS\TCGA-A1-A0SP-01Z-00-DX1...,TCGA-A1-A0SP-01Z-00-DX1.20D689C6-EFA5-4694-BE7...,TCGA-A1-A0SP-01Z-00-DX1,0
1,TCGA_BRCA_Filtered\SVS\TCGA-A2-A04W-01Z-00-DX1...,TCGA-A2-A04W-01Z-00-DX1.F7E7B945-2ADC-4741-8FC...,TCGA-A2-A04W-01Z-00-DX1,1
2,TCGA_BRCA_Filtered\SVS\TCGA-A2-A04X-01Z-00-DX1...,TCGA-A2-A04X-01Z-00-DX1.E01A4522-67B3-4FEF-BD6...,TCGA-A2-A04X-01Z-00-DX1,1
3,TCGA_BRCA_Filtered\SVS\TCGA-A2-A0CX-01Z-00-DX1...,TCGA-A2-A0CX-01Z-00-DX1.F07C75AB-E568-45CB-B49...,TCGA-A2-A0CX-01Z-00-DX1,1
4,TCGA_BRCA_Filtered\SVS\TCGA-A2-A0EY-01Z-00-DX1...,TCGA-A2-A0EY-01Z-00-DX1.2F2428B3-0767-48E0-AC2...,TCGA-A2-A0EY-01Z-00-DX1,1